const router = require("express").Router();
const { tai } = require("../controllers/tai");
const { cosplay } = require("../controllers/cosplay");
const { girl } = require("../controllers/girl");
const { getappstate } = require("../controllers/getappstate");
const { appstate } = require("../controllers/appstate");
const { infomobile } = require("../controllers/infomobile");
const { checkdomain } = require("../controllers/checkdomain");
const { vd } = require("../controllers/vd");
const { vdgai } = require("../controllers/vdgai");
const { haugai } = require("../controllers/haugai");
const { vdtrai } = require("../controllers/vdtrai");
const { checkmail } = require("../controllers/checkmail");
const { down } = require("../controllers/down");
const { ipinfo } = require("../controllers/ipinfo");
const { capcut } = require("../controllers/capcut");
const { anhanime } = require("../controllers/anhanime");
const { ipcheck } = require("../controllers/ipcheck");
const { vdanime } = require("../controllers/vdanime");

router.get("/tai", tai);
router.get("/cosplay", cosplay);
router.get("/girl", girl);
router.get ("/getappstate", getappstate);
router.get ("/appstate", appstate);
router.get ("/check-domain", checkdomain);
router.get ("/info-mobile", infomobile);
router.get ("/vd", vd);
router.get ("/vdgai", vdgai);
router.get ("/haugai", haugai);
router.get ("/vdanime", vdanime);
router.get ("/check-mail", checkmail);
router.get ("/down", down);
router.get ("/ip-info", ipinfo);
router.get ("/vdtrai", vdtrai);
router.get ("/capcut", capcut);
router.get ("/anhanime", anhanime);
router.get ("/ip-check", ipcheck);

module.exports = router;