module.exports.config = {
    name: "ngôn",
    version: "0.0.1",
    hasPermssion: 0,
    credits: "JRT",
    description: "Coppy Ngôn Để War",
    commandCategory: "Kiến Thức War",
    cooldowns: 5
};

module.exports.run = function ({ api, event }) {
    const data = ["Chảnh cầy ” mà cứ tưỡng Fair Play\nNgoài mặt thì thơ ngây\nNhưg bên trog đúg chất mặt DÀY\nXoắn ai ckứ đừg xoắn tao\nĐã là chó ngao thì đừng quá tự cao\nPhiêu cũng sập , đéo phiêu cũng phập\nCảm thấy có thể lấp thì cứ nhiệt tình\nMày nghĩ tao ngán mày lắm sao",

      "Nè thằng chó, ra nghe bố nói này, Ngày xưa mẹ con mất trinh non cũng là vì bố đấy, Rồi mẹ con đái ỉa ra con cũng là do bố cấy, Rồi mẹ mài sinh ra mài như một thằng quái thú, Mỗi lần cho bú tao phải đút cu vào trong mồm mài vì con mẹ mài ko có vú",

      "Dis con mẹ mày á. Mày ăn không ngồi rồi quá, hết việc làm nên đi chửi phải không? Nếu mày đéo có việc gì làm thì mày dắt mẹ mày đi ra ngoài đường với mày, xong 2 mẹ con tụi mày lột đồ nhau ra mà đụ nhau giữa đường cho đỡ nhàn rỗi. Ngày xưa tao đéo có việc gì làm nên tao phải hay đi qua nhà mẹ mày để rủ bả làm trò đó kiếm tiền sống qua ngày đấy. Về hỏi nhà hỏi mẹ mày xem có phải như thế không nhá.",

      "Đời quá chán nên Tao chả ngán đứa nào, xông vô và tao sẽ cho mày đi ôtô ra Nghĩa Địa =))",

      "Loe toe bố lại đập cho vỡ mặt Mồm thì như cái củ cặc lại thích lăn tăn, Mặt thì nhăn nhăn như lồn bà già 78\nCặc có chà giấy nhám cho nhẵn thì đừng có lớn tiếng\nKhông bố lại xẻ ra thành từng miếng mà bôi kinh chó vào cho rát\nChưa kể đầu thì như cái bát đựng phân",

      "Tay chân lại đéo được cân bằng Ngón tay suốt ngày móc lồn chó nên cùi là phải\nMiệng sứt đéo ăn được gì lại suốt ngày lải nhải ra phân…\nChửi thế thôi cho mày sợ, chứ không bố lại banh mồm mày ra mà ỉa vào như máy bay thả bom B52 thì có mà chết cả lò mẹ nhà mày. CÚT",

      "Sống Là phải biết điều\nĐừng tỏ vẻ máu liều nhiều hơn máu não\nNhaa pạnnn– Thích nổi và chơi trội tao sẽ cho mày lên ngôi….\nĐú bẩn mà sấc mày thích thì cứ lên mâm trên mà ngồi!!!\Có điều mày lên nhớ rằng…..\nGiữa chó với người sẽ chẳng bao giờ có sự công bằng.,\nLáo nháo là tao vùi dập thẳng! !!\nDù có cố thể hiện hay là đang nguỵ biện thì ấn tượng của mày chỉ là 1 tiếng ẳng !!\nSống hẳn hoi tao còn phục nha",

      "Tao là gió\nMày là cây\nTao thích tung bay còn mày ngồi yên một chỗ. Cây không đổ mà gió củg chả rãnh để xô cây\nĐéo liên quan thì đừg lên tiếg cắn càng =))\nTao rất đàg hoàg nhưg khi chọn bạn chơi đúg kiểu. Chứ cái thứ chơi đểu thì phắn mẹ nó đi =))\nTao tuy hiền nhưg củg khôgg ngại mày làm phiền tới tao\nMột khi tinh thần ác quỷ đã dâgg cao\nThì mày sẽ lao đao và kết quả ra sao chính là do mày tự tạo :)))))",

      "Cuồng dâm sinh hoang tưởng vừa thôi cô bé ơi có như thế nào thì cũng đừng tự ỉa tự ăn thế chứ chị có ntn thì cũng đéo đến lượt e dạy chị đâu.\nE có tự nhận mình đoan trang thì cũng biết e là con phò quốc tế rồi. Hà Thiên Lộn ạ!",

      "Đéo có ăn có học gì suốt ngày chân hình cái phễu nó khổ thế đấy! Có vẻ là học sinh có vẻ là lừa tình nhưng ngực thì phụ huynh còn lồn thì thành cựu chiến binh cmnr e ơi đã nát rồi thì đừng để mình thêm bể nữa.\nNhìn mà thương cho cái ng mà đẻ ra e quá! Bố làm cả tháng đúng là ko bằng con dạng háng một đêm…\nĐừng làm những trò lố để chứng tỏ mình ko có não nữa e à!",

      "Con lồn âm trì địa ngục tội lỗi tầy trời nay lên đây để gây với mẹ mày thì mẹ nguyện xé thịt xé xương mày cho chó ăn Thứ đầu trâu mặt ngựa như mày thì có mà úp mặt vào lỗ đít chó nhà mẹ mày chứ hay ho gì đâu mà vênh cái mặt lồn cầm thú của mày lên đây nói chuyện với mẹ Máu lồn tháng này của mày dồn lên não của mày hết rồi ha gì vậy con lồn quái thai không biết trời cao đất rộng nên đòi dập mẹ mày đúng không\nĐi war được vài ba trận học lỏm được vài câu ngôn phèn như dái chó mà đòi đú war với mẹ mày hả Ngôn của mày như giẻ chùi lồn rách hơn con đỉ lồn 3 bến sông nước vẫn chưa rửa sạch mùi lồn của mày đó con nghiệt súc ngôn của mẹ mày đủ dập đầu con quái thai như mày xuống 18 tầng địa ngục đó Đừng ở đây múa mép thể hiện mình trình cao bại trận mãi là bại trận thôi con chó cái ơi\nCái trình của mày là trình con kiến mày hiểu không tin mẹ mày dập con súc sinh như mày hồn bay phách lạc 4 phương 8 hướng mấy câu ngôn như bú buồi mà lên giọng mẹ với mẹ mày xem mẹ mày có đá mày chết đĩ mẹ mày không ? Mẹ cho mày 5s Bước ra đây đạp đầu xin lỗi mẹ mày hay để mẹ lôi đầu mày cắm xuống đất mới chừa hả con đầu trâu mặt ngựa",

      "Phải chăng năm xưa a m trám xi măng vào lỗ âm đạo như động phong nha của con đĩ mẹ mày lại rồi, thì năm nay tao đã không mệt mỏi trừng trị con quái thai lai chó tồn tại ở dương gian mà không biết trung thành với chủ rồi vò đầy bứt tóc nãy giờ từ phía xoáy 180 độ cũng không rặn ra được câu nào hay ho ra trò lẩn quẩn mấy câu như lồn nhả ngôn nghe ung thư tai biếng vậy mà cũng bất chấp sủa",

      "Mặt chó mày có lén la lén lút thì muôn đời ngàn kiếp vẫn đéo xứng tầm a đâu nhé con ranh đú đởn\nAnh mày hiên ngang sải bước trên thảm đỏ còn mặt lồn mày thì là đứa hầu hạ đeo bám phải quỳ xuống chùi giày chùi dép cho chị để a có cơ hội đạp đầu mày bước lên đến đỉnh vinh quang vẻ vang rạng rỡ a nói mày nghe chị không nói mày cũng phải tự hiểu là mặt cặc mày không tiếng không tâm đi đến đâu dân chúng cũng đè đầu cưỡi cổ đạp đổ bát lư hương nhà mày đứa không biết điều như mày chị đây phải trụng cái thân cái xác mặt chó mày nước sôi cho trày da tróc thịt lột xác thành một con người mới may ra còn có thể tránh việc mày hiên ngang vỗ ngực xưng danh mày bố thiên hạ mẹ thiên nhiên nhưng đáng tiếc thay bị chị mày bắt gặp rồi lôi đầu mày đá vô lại bụng con gái mẹ mày cho mày được tái sinh mang hình hài một con người kèm với bộ não đầy đủ chất xám một lần nữa cho mày bỏ cái thói huênh hoang trước mặt tao nhé con nô lệ tình dục",

      "Gái mẹ mày ngông quá vừa ngông vừa ngu-))não nhồi nhét cứt hay gì mà đéo thông nổi câu tao nói?",

      "Mày tin chị mày cắt cu thằng cha mày xẻo háng con gái mẹ mày vì cái tội đéo biết dạy con để con ăn nói hàm hồ mất dạy với người lớn không?🤗",

      "Vở kịch này có bao nhiêu ”khán giả” ?\nMà sao mày cứ vất vả ”nhập vai”.\nCuộc đời này đâu trả ”Cát-xê” ai? Sao mày cứ đam mê mà ”diễn xuất”\nTự tao hiểu mày thay đổi đó là điều hiển nhiên. Tháo chiếc mặt nạ ra và tự hỏi với mình rằng mày trong gương hay 1 con quái vật.\nTìm đâu xa quỷ giữ khi nó đã thối nát ở trong tâm hồn mày bấy lâu! Nói thật là nhơ nhớp vice car lone ;))",

      "Nhỏ 0 học lớn não 0 nếp nhăn ròi đi ra phán xét người khác hả trời ranh con mặt mày thì đẹp trai xinh gái ròi mới vác mặt chó đi ra nói này nọ người ta ta mặt đẹp mào nết xấu thì cũng chỉ chơi với chó súc vật thôi chứ chơi làm sao được với anh hả. Tính nết như uống nước cứt vậy mà đòi dẫm bẹp ròi va anh vậy ôn núp háng đi địt cả năm giờ 0 được địt nữa thì đi va à nói chuyện như vả lòi mõm lồn ra nha ròi anh vứt cho chó ăn cho mày đéo toàn thây banh lồn bửa cặc ra mà khỏi siêu thoát nha đĩ ơi Xàm cặc ròi muốn bợ đít ai dí anh hay là mày chỉ lết lết dưới chân anh ròi nói được vài câu là nín họng chó vậy mấy đứa có não mà 0 suy nghĩ được thì  vứt mẹ não đi khỏi dùng táp cho lật mặt lồn ra thì kêu anh ngu ròi chó này nọ nha não lồn muốn địt thì xéo lại lồn má mày mửa zô đó ròi địt cho tung lỗ lồn má mẹ cưng đj chứ ở đây làm tốn thời gian còn làm anh phí ngôn nữa cái thứ mặt lồn đầu cặc dơ dáy à. Buồi cha lồn má mày 0 đù dùng thì đi làm đĩ hoặc là làm trai bao cho đỡ nứng chứ lết vậy dơ bẩn quá đó. Nết mày như kiểu người ngoài hành tinh xuống trái đất bị người ta túm đầu lôi ào lâu xanh bán cho trai mỗi đêm ư ử như chó cái đang tới thời kì động dục phát tiết cho chó đực ngừ lồn ròi đọt nha nói chuyện có não mà như não chứa cứt thì mày cũng chỉ làm súc vật ba hoa thôi cưng ơi. Nói cưng 0 hiểu thì lại xúc phạm con chó còn cưng thì nết như súc vật đầu buồi thì cưng lại tưng lồn cửng buồi lên cắn nói này nọ mất công anh kêu pet anh dịch nữa nết lồn như mửa cứt zô họng thằng già địt má mày á Ba hoa xàm lồn đi chê này nọ ròi nghĩ vậy là hay là ngầu rồi anh kêu người vào dí mày 0 trượt cái nào lúc đó về mách mẹ ròi núp háng mẹ đéo khác nào chó núp lùm nka ôn, anh chưa đá cưng lọt lại háng má nằm trong đó ngâm rượu nha lồn hôi buồi thối dơ dáy tới mức anh buồn mửa vào họng cho mày ăn hết chứ thứ như mày ăn cơm thì tốn gạo còn sống thì chật đất anh biết anh 0 đẹp nhưng cưng đâu có nuôi anh được ngày nào dạy anh được câu nào mà lên giọng đòi kéo đầu anh trời não còn thì cưng 0 suy nghĩ vậy đâu loại não tàn đồ trụy muốn liếm lồn má bú cặc ba thì sảng cứt ở đây mà nhảm lồn với anh. Cái thứ người có nết 0 bằng súc sinh thì mày nghĩ mày ra oai được với ai cưng nói chuyện như con vặc dí lồn đĩ mẹ bao thằng cha mày hả nghĩ ra đây phán xét vài câu là hay ròi ra oai anh táng nát bét lồn rách nha. Ranh con anh trù cho cưng núp trong bãi rác còn ăn thì bốc cứt đẻ con thì đéo có lỗ đít để ẻ cho mày ăn rồi con trai thì buồi cụt còn con gái thì lầm đĩ nha😭",

      "Âm binh khí đụ 3hồn 7vía mày trụ lạc phương nào nghe lời phù phép của mẹ mà khôn hồn về đây mẹ nghe mẹ hỏi tội, trời chu đất diệt thằng ôn vô tri vô thức đầu ốc tứ chi bin liệt phụ lòng tin tưởng ngày nài cũng bị lấy lồn ra làm bồn chứa tinh để sinh ra được thằng con như này có đáng không? T trách tại sao lúc mới lọt lòng mày  chúa tr lại không ban cho m đầu ốc thông minh đầy đủ lại ban cho đầu ốc thiếu suy nghĩ như lấy để trưng bày trong viện bảo tàng mãi không ngóc đầu lên được sống trong tâm tối chúa trời sai tao xuống đây để mở sáng đường cho mày lại không biết tận dụng lại còn giựt mòng lên ẳng ngang với mẹ sao ? Mắt mù đui lọt tròng hay sao không tự phân biệt đc 1ng đứng trên vạn ng 1 ng ngư đống rác trơi sông khống i để tâm muốn làm tâm điểm của mọi người thì thiếu gì chuyện để làm lại đi kiếm chuyện với bậc mẫu nghi như t? Ngổ ngáo hổ báo mảnh hổ tới nào mày cũng phải nghiêng mình kính chào chị m mà thôi tốt nhất thì dập đầu xuống xin lỗi chị nhanh chị tha còn không mẹ đập đầu mày xuống đống máu kinh chó hôi tanh bẩn thỉu cho mày suy nghĩ về nhân cách thối tha + cái não bại liệt của mày ? Mẹ là thiên sứ được đấng tối cao cử xuống để khai sáng mở đường cho mày nói lời ngọc ngào không nghe thì mẹ đây ra tay bạo lực lại trách tàn nhẫn với mày? Chị đây nhân từ như đức mẹ không lòng lang dạ sói như loài cóc ghẻ toàn là lời nói mật ngọt nhưng lại chả ra tích sự gì mẹ đây thay tr hành đạo dạy dỗ đứa con nghịch tử như mày thay bame m có công nuôi dạy mà lại sinh ra thằng bại não 😔 Giấu đâu được bản chất thú tính của con súc vật não ngắn như mày? Múa may quay cuồng trong mơ hồ không tỉnh dạy làm chị mày đây dốc  hết tâm hơi vào để gõ phím với loại hạ đẳng khép nép e dè dưới mép lồn t? Sai thì lết ra mà xin lỗi thì đâu phải bị mẹ dí chạy hục hơi tí tắt vào rừng sâu cop từng cái ngôn bận hèn hạ cùn như z? Vỗ ngực xưng danh thánh nhân hay là thuốc tính ấu dâm khách quen tửu lầu xanh? Gõ không lại mà lại lăn tăn đi gõ với chị sao bệnh hoang tưởng đó có cần chị chữa cho mày hết bệnh xong phải quay qua cung sùng chị m lên không? Ăn hôi bợ đít thấy những sớ ngôn phụ khoa dài dòng ra rồi ríu rít làm cái đuôi theo sao cung phụng nhau để rồi khi gặp chị mày lại e dè nhút nhát như thỏ con trong bị mẹ nắm đầu dập xuống đống rác, muốn tháo chạy có chạy đằng trời cũng bị mẹ nắm gọn trong lòng bàn tay đời đời quy tổ quy tông nhà m mãi mãi không ngốc đầu lên đc vì xấu hổ nhục nhã khi sinh ra thằng nghịch tử bất tri bất diệt. con đĩ mẹ mày.lm mấy cái ba hoaaa xàm lồnn tưởng v là hayy shao?🤕",

      "Đái cu sửng văng vào mổm ăng khôn ra cần chi gặp chị em tự sử nc đái dơ thôi của bé dẹo bị bắt giữ và phát triển kinh nghiệm của các nhà khoa học công lập acc bot chs có j ăn cã 2 vợ chồng tôi cũng kiếm được nhiều người thì 10 mấy triệu USD để mua acc khác mà không cần phải có một người bạn của bạn sẽ có tiền mua nhà ở nhà ở xã hội sủa và có nhiều đâu mà mua acc khác mà không cần phải văn phòng phẩm sách cái bao tử đó có cả những người khác thích điều kiện mua bán nhà riêng tư của anh ấy có một số hình ảnh vậy cẻn có j ăn hết một mình trong tích xưa cùng tham khảo đc phép bị phạt tù từ từ sẽ mất bã nhờn và mụn có một người bạn của mình kiếm sống bằng nghề của bà làm việc tại các thứ cần anh lo am bờ sông Hồng Liên quân đội quần lót của em đâu có gì là không được phép nghe lời em nói em không biết có phải em đã uống thuốc an thần chr có kìa sao ko ạ em cảm thấy rất vui vẻ và hạnh phúc và thành công chúa nhỏ mà không cần thiết để em đi tắm đây cũng ko biết bé nó có tác 7 1 lần nữa lại về nhà r thoải mái đi ý nghĩa của anh ta lại có mất cái vậy mà anh t t là sao hả bạn thân của em đâu",

      "đĩ thì cx có 3 7 loại đĩ như m thì đĩ j z t\nĐịt lất phất như mưa rơi, địt tơi bởi như bom đạn\nĐịt lãng mạn như Romeo và Juliet\nĐịt khoét cái lỗ sâu, địt khắp cái lỗ bướm\nĐịt đứng tim phổi, địt cặp mắt nai\nMà địt chai lỗ đít, địt khít cái lỗ lồn\nCon đĩ mẹ mày, mà tao địt con đĩ mẹ mày\nNhư gà mái mổ giun, như chó càn cắn dậu\nThằng cậu mày hiếp dâm, tao bật cái cánh cửa\nCho con mẹ mày nằm ngửa, bửa nát tử cung\nKhai thông buồng trứng, hứng full tinh trùng\nĐịt bồi hồi cảm xúc, địt như bánh đúc ra lò\nĐịt như mấy con phò bên hồ Hoàn Kiếm\nĐịt như mấy con điếm bên chợ Đồng Xuân\nĐịt đằng chân mà lên đằng đầut\nĐịt lất phất như mưa rơi, địt tơi bởi như bom đạn\nĐịt lãng mạn như Romeo và Juliet\nĐịt khoét cái lỗ sâu, địt khắp cái lỗ bướm\nĐịt đứng tim phổi, địt cặp mắt nai\nMà địt chai lỗ đít, địt khít cái lỗ lồn\nCon đĩ mẹ mày, mà tao địt con đĩ mẹ mày\nNhư gà mái mổ giun, như chó càn cắn dậu\nThằng cậu mày hiếp dâm, tao bật cái cánh cửa\nCho con mẹ mày nằm ngửa, bửa nát tử cung\nKhai thông buồng trứng, hứng full tinh trùng\nĐịt bồi hồi cảm xúc, địt như bánh đúc ra lò\nĐịt như mấy con phò bên hồ Hoàn Kiếm\nĐịt như mấy con điếm bên chợ Đồng Xuân\nĐịt đằng chân mà lên đằng đầu t\nĐịt lất phất như mưa rơi, địt tơi bởi như bom đạn\nĐịt lãng mạn như Romeo và Juliet\nĐịt khoét cái lỗ sâu, địt khắp cái lỗ bướm\nĐịt đứng tim phổi, địt cặp mắt nai\nMà địt chai lỗ đít, địt khít cái lỗ lồn\nCon đĩ mẹ mày, mà tao địt con đĩ mẹ mày\nNhư gà mái mổ giun, như chó càn cắn dậu",

      "Dòng thứ con đĩ đầu thai chuối ôn chuối ngục, năm xưa cho mày hốc tinh trùng nhiều quá rồi nên đâm ra mày hãm lồn\nCái lồn con đĩ mẹ mày trên mạng thì gõ phím như một vị thần, ra ngoài gặp tao chắc cái mặt xanh rờn như tàu lá chuối xách cái lồn chạy 8 kiếp. Bà già mày 1 phút nứng lồn mà đẻ ra con quái thai đầu trâu mặt ngựa não tôm như mày mà lại còn đéo biết dạy mày thì hôm nay để bố mày thay trời hành đạo để không tốn công bà già mày đẻ mày đau lồn.\nDòng thứ súc vật đầu thai mà đòi sánh vai ngang với chị mày, cứt chó mà cứ tưởng cục socola america, đụng ai chứ đụng tao thì tao tông cho mày nát cái lồn văng 8 thước nhee con đĩ lồn bá dơ. Tính thì như con cave hạng phèn mà cứ tưởng mình là công chúa trông lâu đài nguy nga\nCái lồn mẹ mày thứ cuồng dâm nên đâm ra hoang tưởng thì để tao kêu xe tông cho chột cái lồn mẹ mày luôn, thứ đĩ như mày cho ăn xin còn không thèm đụ thì mày nghĩ mày là ai\nCoi chừng tạo nghiệp nhiều mốt đẻ con tàn tật thì lại khổ cái con đĩ mẹ mày nghe chưa. Tranh thủ kiếp này bớt đi nứng lồn dạo làm chị đại bàn phím để mà tích đức cho con cháu sau này nghe chưa ?\nChị mày nói ít mong mày hiểu nhiều chứ cái loại ngu như mày thì đụ má nói nhiều hiểu cũng đéo được bao nhiêu.",

      "Đến chó quát nó lúc nó đang sủa nó còn im. Đằng này t ns m tử tế m kòn chả nghe chứng tỏ m chả bằng con chó nhà t. Sống thế nào cho thơm đi m. Toàn muốn làm rác rưởi bốc mùi thối cho xã hội\nThứ âm binh đầu lồn ăn cơm đậu phụ đi bàn chuyện chính phủ, Tiếc cho cái mặt xinh mà trí thông minh thì đéo có nhân cách lại méo mó, mày thích làm chó thế sao?\nCống rãnh đòi sánh vs đại dương, kênh mương đòi tương đương vs bể nước.\nĐầu đầy tóc – óc đầy phân. Đầu là nhân – mà thân là chó, quá uổng cho một kiếp người.\nBẩn như rận mà muốn làm Thiên Thần- Rách nát rã rời lại ước mơ làm Mẹ đời thiên hạ, tao khờ nhưng t biết thứ nào dơ, hứ dơ như m chỉ cần t nhìn sơ là nhớ.",

      "Cái thứ ăn hại mà còn tỏ ra mình có tài. Nhai lại mà còn nghĩ mình là Nice\nChó cắn áo rách, mà sao áo lành vẫn không tha, chửi mày chỉ sợ không hiểu tiếng người còn đánh mày thì người ta bảo chị đây ngược đãi động vật.\nNhìn mà thương cho cái ng mà đẻ ra e quá! Bố làm cả tháng đúng là ko bằng con dạng háng một đêm…\nNhững đứa hay đi săm soi nói xấu người khác như thể loại xàm cặc như mày nó chỉ thấy hạt cát trên đầu người khác mà không thấy cái sọt rác đang đội trên đầu mình\n",

      "Địt mẹ nhà mày phò rồi mà dám vỗ ngực xưng oai cứ tưởng mình là thiên nga à em, anh lại vả vào lồn con hãm cặc tai ương chướng nghiệp óc đầy máu bướm của mày , con âm binh thú rừng đụ mẹ mày cắn ai vậy đĩ, súc vật vẫn mãi là súc vật thôi con ranh:)) cần tao lấy xô nước đái dội vào đầu mày không gái mày còn thích ở đấy cà nhay cà chớn em bung đôi ba cái ngôn xàm lồn ba hoa hay sao kì này để anh đẹp đục lồn mày sâu 10 đáy biển địt cụ em có cần anh đây phải kéo lồn e toè hoa, bung chỉ dưới sàn nhà không, war mxh nhảm lồn đi xét kèo real em không thấy rằng mình nhục cặc hả óc vậy, war được vài ba trận thắng cứ tưởng mình hot war anh đẹp cười ỉa máu lồn vô bản mặt mày, nứng quá thì đi kiếm đĩ mà chơi chứ ở đấy mà ngông hết phần thiên hạ cop ngôn của gg thì câm mẹ cái mõm vào đi anh lên đây để bày tỏ sự ngu dốt của tao để cho cái nhân cách lồn của mày thấy tao không như xưa nữa con phò bập bẹ bước vào sàn war mà dám xưng oai ngôn mày từ phụ khoa hay vì mà chả có dame gì với anh giạy bé có cần anh em tao rap cho mày nghe ko con phò ngụ ngôn kia ả tiện tỳ dơ bẩn em núp dưới háng anh tụng kinh gõ câu ngôn như ruồi muỗi bay qua mặt anh và để anh em tao bóp chết moẹ em ngồi nhai đi nhai lại về cái ngôn phụ khoa của e mà anh tức nước vỡ bờ cầm chổi chọc nát lồn em, em cầu xin anh tha cho cái mạng chó rách của mày chứu ngồi đáy mà nhả mấy cái ngôn tầm thường anh mày vẫn đủ trình để đáp lại mấy cái ngôn rẻ rách mà mày gõ ra đĩ mẹ mày đừng để bố đào mồ quốc mã ba họ tám sông lỗ lồn nhà mày đừng để bố địt từ trên cao địt xuống từ phát cuối đến phát đầu tiên địt phải địt như bố mày địt từ mùa hạ sang đông cái lồn mẹ mày có phải lồn axit lồn khít như lồn trâu khô lồn khôn dái chó lồn bó dái người cái lồn mẹ mày có phải đêm nào cũng nhảy sexy như con điếm cave quái thai mồm hôi nách mồm thối con lồn thô tục con lồn trà đá thuỷ tinh đục vô cái mu lồn tinh trùng mày, con lồn một tạ con lồn bóng rổ con lồn bóng bàn lọt sao nồi cháo đang sôi sùng sục cắt lồn mày ra thả vào làm cháo lồn cho ông cố nội mày ăn trù bố mày thử vận khí công tông vô cái mu lồn rách nát nhà mày hay để tao địt con đĩ mẹ mày như anh hùng mua kiếm địt cái lồn bung hoa như hoàng châu cách cách:))? 🔥",

                  "Đừng cố tỏ ra vẻ hiền lành rồi lại để lòi cái đuôi cáo, cái thứ tai tiếng mà tưởng mình nổi tiếng như cưng thì làm sao có trình mà gõ với mẹ đây, về bú vú mẹ rồi ngủ trong mơ 10 năm nữa có khi mình ngang cơ, tưởng mình thông minh nhưng thật ra não như con tôm trong đầu chẳng có gì ngoài cứt, lồn thâm rách nát mà đòi sánh với cái lồn con trinh, tư cách của một con đĩ như mày mà cũng đòi mở mồm nói đạo lý cơ đấy. Ra đường phải nhớ nhìn trước nhìn sau chứ không xe container nó mất lái nó lại ủi vào cái lồn con đĩ mẹ mày đó con nghiệt súc. Đã ngu thì câm mẹ mõm lồn lại cho người ta thương chứ đừng có xàm cặc nửa nạt nửa mỡ cho người ta ghét, lời mày thốt ra hãm lồn đến mức gây tổn hại cho bầu không khí này nên không nói được gì tốt đẹp thì thôi dẹp con mẹ mày đi, sống đéo tử tế thì tử vong mẹ đi cho đỡ chật đất. Nói ít nhưng hiểu nhiều chứ giống loài máu lồn nhiều hơn máu não như mày thì nói nhiều cũng chả hiểu được bao nhiêu đâu con đổn lì ạ",

      "Cái loại như em mẹ đẻ ra đau lồn não đúng là toàn cứt người ta nói còn đéo hiểu tiếng người kìa đụ mẹ cái loại nứng lồn thì phanh lồn ra bà mày cho mấy chục con chó ghẻ ra địt cho nát lồn mày nè con tao nhân nhượng là mày lấn tới hả địt mẹ cái loại não toàn tinh trùng trộn với cứt nứng thì dùng sex toy hay ra đường phanh lồn ra cho mấy thằng già địt ý cái bản mặt mày còn đéo bằng mặt con đĩ bị địt cho rách lồn trong nhà thổ kìa mặt dày thì dày vừa thôi để người ta dày với não ủng nước toàn cứt với tinh trùng, tinh trùng với trứng của bố mẹ mày chắc không tệ đến nỗi đẻ ra đĩ như mày đâu bà lại lấy gậy đập nát lồn mày tử cung nát làm trăm mảnh trình chị đủ để tét nát mu lồn em nha cưng  nhờ đĩ lồn đê tiện như e đẻ ra đau lồn lại vô tích sự Sống mà sân si đê tiện như thế sau này cũng có lúc bị đập nát cái ảnh đại diện thôi em à sống cũng phải để người ta nể chứ bé ngu thì ngu vừa vừa thôi có cần chị tét nát mu lồn nhét cứt vào não cho nghĩ thông suốt lại không bé để cho xã hội người ta đến nhà đáp cứt vào cái bản mặt đê tiện đéo bằng 1 con đĩ bị địt rách lồn như mày chắc bố mẹ xấu hổ hộ bé ơi tội cho bố mẹ mang nặng đẻ đau 9 tháng 10 ngày đẻ ra đứa con đê tiện mặt dày đéo bằng đĩ đứng đường như mày Đừng tưởng chị hiền mà em cứ được đà lấn tới nha cưng đã bảo cút thì tự vác cái lồn mày đi mẹ đi  Chị thân thiện nắm nên nà đừng để chị nóng lên nà e khum có cứk mè ăng đou nhó Lôi cáii lồn thâm hơn dái chó của bé lên đây nói chuyện hẳn hoi với chị nào  Chánnn thế bé ơi:((( Lôi bản mặt đê tiện sân si nứng lồn của bé lên đây nch zuii zẻ nèooo babe đọc địa chỉ chị ship cho bé ít bô mà đội lên đầu nà Bé khum thít bô thì chị ship cko bé mấy cân trà xanh dưỡng lồn bé nkaa nhớ uống để lồn bớt thâm bớt sân sii đii nkaa:33 Hayy nà chị ship cho bé ít sextoy thông nát cáii lồn bé nkaa hư waaa sau này cứt không có mà đớp vào mõm đou nkaaa bé vác cái mu lồn lên đây nch hẳn hoi với chị đi bé. Vài ba cái ngôn xàm lồn lủng cà lủng củng của bé mà đòi so sánh với chị ư?? Mơ mà ngủ kìa cưng cha mẹ mày địt nhau 69 tư thế ai ngờ đau đẻ ra con quái thai như bé. Ngôn của cưng sát thương chỉ đủ chết 1 con muỗi mà đòi đá đít chị thật là ảo tưởng mà. Loại như bé chị đá cho bay qua mấy cái Bắc Băng Dương với Đại Tây Dương xuống tận địa ngục ma khè chắc cũng chưa biết sửa lại cái tính ngông lồn của bé đâu nhỉ??? Ngôn của gái làm chị cười sảng ý gái thật là hài hước cái loại như gái phanh lồn uốn éo giữa đường trai nó cũng đéo thèm dí cặc vào cái loại tiện nhân quái thai vô liêm sỉ tự cao tự đại mình là cóc ghẻ xấu ỉa mà cứ tưởng thân là thiên nga. Gái lấy mấy cái ngôn xàm xí của gái từ mấy box war xong đòi so sánh với chị mỡ này nhảy vào húp đi con đĩ lồn thâm hơn dái chó mày đừng tưởng chị ỉm đi là được đà lấn tới nha chị còn chưa xé lồn mày làm trăm mảnh ngâm rượu cho thằng bố mày uống là còn nhân nhượng chán đấy gái à",

      "Con ôn lồn nào réo tao bước ra đây địt mẹ con ngáo dái này hãm cứt bấu buồi à mà réo tên t miết thế?Tao dùng xe tăng đứt vào mồm cho mày nín họng nhé?cầm nhân cách mày ra để tao chùi đít còn để tao giựt tóc mày chùi buổi cho tao ,con đĩ tai ương nghiệp chướng đầy mình thân xác khác đéo gì một con chó mà cứ réo tao thế?Loại như mày một phát là chị đây đá mày vào thẳng cái bụng bầu mẹ mày đấy?có phải lồn mày bị chó gặm xog liệt mẹ não rồi không?Con lồn ba hoa xàm địt như mày cứ dổng mõm chó lên mà vỗ ngực xưng danh với tao?ủa sao làm người đéo muốn muốn làm chó thế đi war mẹ mày khinh nhất mấy cái thành phần dơ bẩn ngu ngục như mày đấy chửi nhau vẫn tam táp nhảy vào mà vướng mắc cái lông lồn con ranh con nhảy đổng nói câu ẳng ẳng của mày để tao dìm chết cụ mày xuống 18 tầng địa ngục liếm lồn ma nữ treo ngược đầu con thú hoang thân tàn ma dại của mày lên cho thiên hạ chỉ trích con hãm cặc như mày con nghiệt súc bị tao dẫm đạp con quái thai quái thú nửa người nửa chó thế mà mở cái mõm ra chó này chó kia con khùng lồn xía mõm để tao sục chết tổ cụ nhà mày đi chứ con nghiệp chướng nứng lồn quá nói tao tao dẫn mày ra cột điện rồi đưa cái lồn mày vô đụ cho hết nứng chứ nứng lồn quá vậy ngồi đéo ai động đến lông lồn nào của mày mà cứ ngông mõm chó lên cắn như thế?Dập em như loài hoa hồng nhỏ nhắn mảnh khảnh dập nát đời em như đời bạc phận của chị em thúy kiều dập lồn em như thúy kiều thấy kim trọng xách cặc chơi gay với trương sinh làm nhành hồng thúi hèn như cuộc đời lênh đênh của em ra đây diện kiến mẹ?",

      "Mấy con đĩ tai ương ngóc đầu lên nhìn chị mày nè gõ được vài ba câu ngôn cứ nghĩ mình lên dân war real nhưng ai ngờ là dân war fake thôi bé, tao sẽ là người đạp lồn mày xuống 18 tầng địa ngục dí con cặc bự vào lồn mày cho mày rên lên ôi mấy thằng đàn ông cũng mê cái lồn nhiều lông của mày trông mùi thối bốc ra từ bướm mày rồi thật kinh tởm cho cho những con người xung quanh mày, được bú buồi trai nên ra dáng con phò trước mặt mọi người,gái đã nứng rồi thì banh lồn ra tao gạ cho mười anh địt nát lồn mày nha con đĩ của thế giới, mày bị thiếu ăn hả suốt ngày húp tinh trùng vậy con phò quốc dân?trong bầu không khí ô nhiễm do mày tạo ra đã làm trái đất sắp bị ô nhiễm mức nghiêm trọng nên tao sẽ chặt xác mày ra thành từng mảnh rồi đầu mày tao sẽ cho chó gặm đến lòi hai con mắt lồn của mày ra còn lồn mày thì tao sẽ đá bay ra khỏi vũ trụ này rồi đá văng cái nếp ngông cặc của mày ra khỏi thế giới này păi con uống dâm thủy thay cơm nha con lồn mãi mãi liếm chân dòng họ nhà tao",

      "Đụ mẹ mày con ôn lồn tu phách như mày dơ mà dơ từ lúc sinh ra kiếm sục co đĩ mẹ mày hả con phò nát sủa tiếng chó hoang mang tán xéo mỏ lồn mày liền Để đào mộ con gái mẹ mày lên h saoo hay giờ kêu thằng cha mày đụ nát lồn mày hả em đụ cho tinh trùng dơ tinh trùng khuyết tật nó sồn lên não mày được mày bớt ngu lồn lại",

      "Địt mẹ chị tạt tai lai ranh thằng phò nha địt mẹ chửi chị chị vặn cặc ra làm 5 6 mảnh chứ ở đó ba hoa chị cạo chụi lông cặc cần tao nhét máu lồn vô cái mồm mày không mà ăn nói xàm lồn vậy war ngôm cop chị ịa phọt cứt vô mặt cưng đừng có tưởng chị mày hiền nha chị quay lồn cho vài con đĩ ngông nghênh đó địt mẹ tao chôn sống con mụ nội thằng cố ngoại con bà già nhà mày phải tu 10 kiếp mới được như mẹ mồm còn hôi sữa chó mà đòi đi war à chị nhét cứt zô cuống họng lồn nhà mày đó bập bẹ lên sàn war oai cái máu lồn cha đẻ nhà mày chị đục cái mặt lồn nhà mày ra nha thằng phò non ngôn lồn chơi cop ngôn chị đây ĩa vô mặt chứ đừng nứng cặc lâu ngày cái nước lồn nó thấm zô não mày rồi à ăn nói lăng nhăng xàm chó vậy tao chửi cho 5 đời 7 kiếp nhà mày phải dập cái lồn mu=))",

      "Nhắm bú đít tao hay bú lồn con đỉ má mày chín ngày mười đêm đợi thần thánh nhân danh rồi vác cái bản mặt ra trị tội dùng điệu hổ li sơn ai ngờ nhắm gà trúng vịt đụng trúng thằng cha mày đang đá phò ngoảnh đầu lại thấy hai mẹ con mà muốn cụp đầu khóc lóc lìa tai bị dí tới sứt đầu mẻ trán còn không phục nằm lí xuống giãy đành đạch  như cá chiên mà không cho dầu đợi tao niệm thần chú vong linh gọi cô hồn các đảng xuống nắm đầu con đỉ tam tai nhà mày xuống âm ti khèo quặng sắt đem bố thí thằng cha mày đúc ra cái riều đem đổ đầu thú má mày dập đầu xuống sông Hoàng Hà chừng nào máu đỏ sông trông trời đất thì vớt xác thú má mày lên đây chắp tay lạy phật cúng hồn ba cái để oan hồn chướng khí thú má mày được siêu thoát tương lai khỏi thành cô hồn đợi tháng bảy có chùa phật kinh cúng bái như cho cứt đem về ăn tạm rồi hớp hồn ba thằng ắt ơ đầu đừng xó chợ dùng mỹ nhân kế định tiếp cận thằng cha mày trả lại mối thù năm xưa hay hẹn ước 10 năm chôn nhau cắt rốn xòe ngôn phun nọc độc định hạ thủ cha hạ sát mẹ mà trượt chân té ngã vô lồn của bả xem hai ông bà già đồng tâm hiệp lực nhét mày vô tử cung lọt vào buồng trứng xem cá mè một lứa hai ông cha bà má mày cũng là người sai vặt do tao sai khiến dẫn bảo đến bước đường cùng hóa thành trò tiêu khiển cho yêu ma quỷ quái yêu nghiệt đến làm càn đi cúng ba âm hồn nửa mùa khiếp sau mua may bán đắt giữ lại cái nết sống không bú cu đời không nể tương lai truyền cho con cháu đem đi xả thân cứu nước bú cu chiến sĩ trong chiến trường gọi địch biết ta trăm trận trăm thắng hay kẻ thù của kẻ thù là bạn rủ quân thù đi bú cu bú cặc chung rồi giảng hòa đem lại hòa bình theo cách chính cống mang ra tòa xử tội thì đem lí do bú cu ra thanh minh oan chuộc gọi ma quỷ tới tâng trang mình về động đĩ chuyển đổi giới tính từ mê cu đang liếm lồn sát đất đợi con đỉ má mày chuyển nghề rồi vớt xác bả xuống âm ti cho kinh thiên động địa hả",

      "ngôn đại trà mà cũm đòi type với mẹ à con ôn . Có bị nứng l quá thì lên shopee mua cu giả về mà đút =))) còn nếu đ có thì bảo mẹ , mẹ bố thí cho chứ đừng nứng quá gòi đi kiếm chuyện với mẹ nha con ôn . Mày còn đ bằng cọng lông l của mẹ đâu đừng ở đó kháy nọ kháy kia . Bé còn non với mẹ lắm nên đ đủ trình dập đầu mẹ đâu đừng có mà ngông =))))))) Trình như ngón tay út của mẹ mà đòi dí tao . Mày nghĩ mày phun ra vài ba câu xàm l mà chạy được à =))) Dù mày có sống ở cái xó xỉnh nào thì tao cũng sẽ dập chêt con đĩ mẹ mày nhé . Năm xưa bà già mày biết bao nhiêu thằng đụ mới tìm đến thằng cha tồi để mà ăn ốc đổ vỏ bây giờ đẻ ra cáu dòng máu thối nát cặn bã mày ra để ngông ngông với mẹ =)) khôn hồn thì dập đầu tạ lỗi mẹ để dòng họ ông bà tổ tiên nhà mày sớm được siêu thoát còn kh thì tao túm cổ con gái mẹ mày nha con đĩ chó bớt nứng l lại zùm tao 🙂",

      "Mẹ mày con đĩ lồn mày đó con đĩ chó mặt lồn mày tu luyện mấy chục kiếp cũng đéo cùng đẩng cấp với tao đâu con đĩ lồn bại não 4 chân tap gặp mày tao quật cái lồn mày xoay như chong chóng che của đô rẻ mon lá cái cộng lông lồn mày héo tạn luôn nè gái? Con đĩ lồn mặt lồn âm binh khí đụ mũi đốt cái lồn nổi hột bẩn nết lồn mày chíu sáng ôi tỏ sáng dưới lồn con gái mẹ mày ghê luôn nè đụ đĩ mẹ mày sủa ít thôi mày sủa nhiều như thế cũng đéo bằng taoo đâu mày hãy tập sủa cho tròn Địt cụ lồn mẹ mày con đĩ lồn dơ mày đừng để máu lồn tao sồn lên não nhá gái địt mẹ mày để rồi thì tap cũng dập nát cái mỏ lồn mày à con đĩ lồn tanh ơi nết cặc mày để tao thịnh cho vài con cu giả thông não lồn mày lên não mày cho mày hiểu được tiếng người chứ mày hiểu tiếng phò đĩ tiếng lạt lồn hong à mày khác người lắm huhu tao còn nghĩ trong mày nhìn giống con đĩ mẹ mày ôn lồn quái thaii không nè Mày bớt ảo mà cái lồn mày ảo lên ảo xuống ảo ma canada hay gì con đĩ lồn?",

                  "Bộ lúc ông trời thả não mày cầm ô che à hay máu kinh tràn lên hoà cùng với máu não mày vậy? Trời ơi nhìn cái não mày kìa, sao mà nó có thể trơn tru, láng mịn, không một vết nhăn thế nhỉ? Đại não và tất cả các thành phần trong não mày không phát triển à? Bằng tất cả sự văn minh thành thật mong mày thả lỏng cơ nhai, khép hai hàm lại vì phát ngôn của mày gây ảnh hưởng thiếu tích cực đến chất lượng không khí lắm! Thật thú vị tao nên báo cáo cho tổ chức y khoa thế giới của một trường hợp thai nhi được sinh ra với bộ não rớt ở trong bụng mẹ ví dụ điển hình đó là mày đó thứ ôn lồn não phẳng ạ.\nLưu ý: đừng cố văn minh vì một con đĩ ngu lồn như mày không thể hiểu nổi đâu",

      "Mày thì tuổi lồn ăn được tao nè ôn lồn là saoo má trâu là saooo má hay má cạn ngôn ngữ rồi con đĩ cạn ngôn ngữ hay mày liệt ngôn ngữ hả con đĩ cái lồn bà già con gái mẹ nhà mày con đĩ âm binh âm khí âm lồn đại dương đại bàng nó còn ĩa vô hong lồn mày nữa đó thằng lồn trình ngu giỏi cái sủa ngu chướng tai gai mắt thì t dí",

      "ừ tao nghi si dốt nát còn hơn cái đứa vô danh tiểu tốt sinh ra từ ống cống như mày đấy? nhảm thì nhảm nó vừa thôi chứ nhảm quá tao dùng găng tay của Thanos búng tay một phát thôi là mày bay vòng quanh Trái Đất xoay vòng vòng xuyên 9749292 tỷ năm ánh sáng luôn nhé con ôn. sống thì sống nó ra người đi chứ mày sống mà cái nết đéo bằng con chó nhà tao mà đòi táp tao? bập bẹ nhảm lồn được vài ba câu xàm ngôn bày đặt táp tao là sao em ơi? chị đây đéo muốn nói với mấy đứa thân phận hèn hạ thấp kém ngu lồn như em đâu, nhưng em đã cúi đầu khóc thét cầu xin chị mày thì chị mày sẵng sàng dạy cho em vài câu luôn nè? cái ngôn ngắn ngủn của em người ta đọc còn chán ngắt ra này đặt đâp tao chi để người ta cười vào cái bản mặt vô tri vô giác của mày? đây đâu phải cái cung điện rẻ rách của mày đâu mà vênh mặt lên bắt người ta cúi xuống làm nô lệ của mình? suốt ngày lơ lửng ở đầu đường xó chợ đi phá dân làng rồi phá ruộng đồng nhà người ta sao em chết mà cái nết vẫn i sì con chuột mặc dù đã đầu thai rồi vậy? vô tri vô giác vô danh tiểu tốt sinh ra đã hèn hạ rồi mãi mãi là hèn hạ thôi em ạ, em lôi học thức vào đây chi rồi bây giờ tự làm nhục bản thân rồi vả bốp bốp vào mặt cầu xin chị tha lỗi? chị mày phải lặn lội lên chùa tụng kinh cầu xin cho oan hồn nghiệt ngã không nơi trú ẩn của em được siêu thoát chứ toàn núp ở nhà người dân phá hoại làng xóm như mày sau này Diêm Vương biết lại đì mày xuống tầng 18 lúc đó lại khóc thét cầu xin thì cũng quá muộn rồi em ạ. sống đéo bằng con chó trốn thui trốn rủi trong góc đường thì tốt nhất mày nên đi quét rác hiến nội tạng của mày đi để người khác giữ chứ mày giữ cái nội tạng của mày con phải thốt lên ôi con này hãm nhờ? làm việc tốt để sau này Diêm Vương còn thấy lòng tốt của mày đì mày xuống tầng 10 cho ma trêu quỷ hờn nó lại vo mày lại thành bóng rồi ném qua ném lại cho mày chóng mặt đi ha? rồi lúc đó lại hỏi làm việc tốt mà vẫn khổ ha?",
  ];
  return api.sendMessage(`${data[Math.floor(Math.random() * data.length)]}`, event.threadID, event.messageID);
}