const request = require("request");
const fs = require("fs")
const axios = require("axios")
module.exports.config = {
  name: "nude",
  version: "1.0.0",
  hasPermssion: 0,
  credits: "CallmeSun",
  description: "Random Ảnh Nude  Cực Bổ Mắt ( Lưu Ý Đây Là Lệnh Ảnh 18+ Cân Nhắc Trước Khi Sử Dụng)",
  commandCategory: "Random-IMG",
  usages: "",
  cooldowns: 2,
  dependencies: {
    "request":"",
    "fs-extra":"",
    "axios":""
  }
};
module.exports.run = async({api, event, Currencies}) => {
  var data = await Currencies.getData(event.senderID);
  var money = data.money
  const moneyUser = (await Currencies.getData(event.senderID)).money;
  if (1000 > moneyUser) return api.sendMessage("Bạn Nghèo Vãiiii\nCó 5000 đô rồi xem😼", event.threadID, event.messageID);
	var link = [
     "https://i.imgur.com/0eQqnyv.jpg",
     "https://i.imgur.com/cuViN6g.jpg",
     "https://i.imgur.com/66O6j1T.jpg",
     "https://i.imgur.com/cQ4bk4V.jpg",
     "https://i.imgur.com/AItOYmW.jpg",
     "https://i.imgur.com/AWEW2x0.jpg",
     "https://i.imgur.com/Ot8Gi2c.jpg",
     "https://i.imgur.com/LgCTgHK.jpg",
     "https://i.imgur.com/hxqjQoU.jpg",
     "https://i.imgur.com/mHuLHCa.jpg",
     "https://i.imgur.com/wcPUGG3.jpg",
     "https://i.imgur.com/BHjh6nA.jpg",
     "https://i.imgur.com/TvgODgE.jpg",
     "https://i.imgur.com/vIBxhrD.jpg",
     "https://i.imgur.com/RJvTGPc.jpg",
     "https://i.imgur.com/bwIMkRM.jpg",
     "https://i.imgur.com/dJyMPKb.jpg",
     "https://i.imgur.com/CF1REvb.jpg",
     "https://i.imgur.com/7BZI3Aw.jpg",
     "https://i.imgur.com/RAHnJZX.jpg",
     "https://i.imgur.com/evkUWyk.jpg",
     "https://i.imgur.com/rStVRIk.jpg",
     "https://i.imgur.com/qFe1TVr.jpg",
     "https://i.imgur.com/8RpAroY.jpg",
     "https://i.imgur.com/z6dlAn3.jpg",
     "https://i.imgur.com/fY5PpbL.jpg",
     "https://i.imgur.com/SkpzfPM.jpg",
     "https://i.imgur.com/dyJLuYN.jpg",
     "https://i.imgur.com/kUjlYBk.jpg",
     "https://i.imgur.com/s2atBOe.jpg",
     "https://i.imgur.com/HFNEoY5.jpg",
     "https://i.imgur.com/MxBAE3i.jpg",
     "https://i.imgur.com/odmCEQw.jpg",
     "https://i.imgur.com/NA028eN.jpg",
     "https://i.imgur.com/klHjp8a.jpg",
     "https://i.imgur.com/AXVUcPI.jpg",
     "https://i.imgur.com/24Sj7Rt.jpg",
     "https://i.imgur.com/jBasCnM.jpg",
     "https://i.imgur.com/NTN2r0p.jpg",
     "https://i.imgur.com/qn1MCu6.jpg",
     "https://i.imgur.com/f66CPIM.jpg",
     "https://i.imgur.com/nlvpxyB.jpg",
     "https://i.imgur.com/NQDolOM.jpg",
     "https://i.imgur.com/HnuN8y3.jpg",
     "https://i.imgur.com/938FGA9.jpg",
     "https://i.imgur.com/qKg4GZp.jpg",
     "https://i.imgur.com/Z7lzVgs.jpg",
     "https://i.imgur.com/CzqF4hz.jpg",
     "https://i.imgur.com/piBubnc.jpg",
     "https://i.imgur.com/0aS3h2H.jpg",
     "https://i.imgur.com/fD7X58t.jpg",
     "https://i.imgur.com/9KvVzL8.jpg",
     "https://i.imgur.com/6zNwJtO.jpg",
     "https://i.imgur.com/z11c2wu.jpg",
     "https://i.imgur.com/X0XzqV5.jpg",
     "https://i.imgur.com/fLY88Sp.jpg",
     "https://i.imgur.com/7tBC5gn.jpg",
     "https://i.imgur.com/pzo99ON.jpg",
     "https://i.imgur.com/vc3ITC0.jpg",
     "https://i.imgur.com/xThtzuZ.jpg",
     "https://i.imgur.com/WQk08e6.jpg",
     "https://i.imgur.com/vxWSqCG.jpg",
     "https://i.imgur.com/dyYHbmY.jpg",
     "https://i.imgur.com/VLxDWtX.jpg",
     "https://i.imgur.com/veF8Adb.jpg",
     "https://i.imgur.com/3BgmTB7.jpg",
     "https://i.imgur.com/N1nvEOk.jpg",
     "https://i.imgur.com/4NCgyhq.jpg",
     "https://i.imgur.com/A04IlY9.jpg",
     "https://i.imgur.com/nFLacqd.jpg",
     "https://i.imgur.com/m4TfMda.jpg",
     "https://i.imgur.com/zyXJMzo.jpg",
     "https://i.imgur.com/GbF2pgn.jpg",
     "https://i.imgur.com/NViso5s.jpg",
     "https://i.imgur.com/51Gol0J.jpg",
     "https://i.imgur.com/nPDcrTQ.jpg",
     "https://i.imgur.com/nT9teo0.jpg",
     "https://i.imgur.com/bE5A05z.jpg",
     "https://i.imgur.com/FP4kuJY.jpg",
     "https://i.imgur.com/fnkO96O.jpg",
     "https://i.imgur.com/vKucuuN.jpg",
     "https://i.imgur.com/OHYAXPw.jpg",
     "https://i.imgur.com/FZMvt6Z.jpg",
     "https://i.imgur.com/ZcOnbcB.jpg",
     "https://i.imgur.com/qgRrshJ.jpg",
     "https://i.imgur.com/MFnKafV.jpg",
     "https://i.imgur.com/zJ5YsoP.jpg",
     "https://i.imgur.com/unjK08y.jpg",
     "https://i.imgur.com/I32lYYc.jpg",
    "girl-show-hang-voi-cai-lon-hong-khong-long-co-mot-khong-hai-rv.jpg",
"https://i.postimg.cc/PrXpBQPm/FACEXINH.jpg",
"https://i.postimg.cc/RZq30C1h/gai-xinh-sexy-anhdepeva.jpg",
"https://i.postimg.cc/cLjvtqTm/Gai-xinh-trung-quoc-dang-chup-hinh-nude-thi-bi-nhiep-anh-dit-tung-lon.png",
"https://i.postimg.cc/zXxb5Hg4/gai-xinh-nude-15.jpg",
"https://i.postimg.cc/cHG6TQpt/images.jpg",
"https://i.postimg.cc/hj8vYXny/nguoi-dep-nude.jpg",
"https://i.postimg.cc/wM6MY9T6/Suong-Phe-Cu-Voi-Bo-Anh-Gai-Xinh-Khoa-Than-Truoc-Nang-Chieu-19.jpg",
"https://i.postimg.cc/nr0zHNCq/vu-dep-2.jpg", 
"https://i.postimg.cc/br8DYQLf/Betty-nude-hotgirl-sexy-anh-khieu-goi-gai-xinh-lam-tinh-9.jpg",
"https://i.postimg.cc/RCQJsDVS/clip-hot-girl-show-hang-voi-cai-lon-hong-khong-long-co-mot-khong-hai-rv.jpg",
"https://i.postimg.cc/PrXpBQPm/FACEXINH.jpg",
"https://i.postimg.cc/RZq30C1h/gai-xinh-sexy-anhdepeva.jpg",
"https://i.postimg.cc/cLjvtqTm/Gai-xinh-trung-quoc-dang-chup-hinh-nude-thi-bi-nhiep-anh-dit-tung-lon.png",
"https://i.postimg.cc/zXxb5Hg4/gai-xinh-nude-15.jpg",
"https://i.postimg.cc/cHG6TQpt/images.jpg",
"https://i.postimg.cc/hj8vYXny/nguoi-dep-nude.jpg",
"https://i.postimg.cc/wM6MY9T6/Suong-Phe-Cu-Voi-Bo-Anh-Gai-Xinh-Khoa-Than-Truoc-Nang-Chieu-19.jpg",
"https://i.postimg.cc/nr0zHNCq/vu-dep-2.jpg", 
  ];
   Currencies.setData(event.senderID, options = {money: money - 1000})
   var callback = () => 
   api.sendMessage({
    body:`→ Là Nude đó😼\n→ Số ảnh hiện có: ${link.length}`,
    attachment: fs.createReadStream(__dirname + "/cache/nude.jpg")
  }, event.threadID, (err, info) =>
        setTimeout(() => {api.unsendMessage(info.messageID) } , 10000));
       request(link[Math.floor(Math.random() * link.length)]).pipe(fs.createWriteStream(__dirname+"/cache/nude.jpg")).on("close",() => callback());
   };